import contarOvejas from "./src/01/index.mjs";
import listGifts from "./src/02/index.mjs";
// const isValid = require('./Challenge03/index');
// const createXmasTree = require('./Challenge04/index');
// const daysToXmas = require('./Challenge05/index');
// const sumPairs = require('./Challenge06/index');
// const contains = require('./Challenge07/index');
// const maxProfit = require('./Challenge08/index');
// const groupBy = require('./Challenge09/index');
// const getCoins = require('./Challenge10/index');
// const shouldBuyFidelity = require('./Challenge11/index');
// const getMinJump = require('./Challenge12/index');
// const wrapGifts = require('./Challenge13/index');
// const missingReindeer = require('./Challenge14/index');
// const checkSledJump = require('./Challenge15/index');
// const decodeNumbers = require('./Challenge16/index');
// const countPackages = require('./Challenge17/index');
// const fixFiles = require('./Challenge18/index');
// const learn = require('./Challenge19/index');
// const pangram = require('./Challenge20/index');
// const canCarry = require('./Challenge21/index');

(() => {
	console.log( contarOvejas([ { name: 'Noa', color: 'azul' }, { name: 'Euge', color: 'rojo' }, { name: 'Navidad', color: 'rojo' }, { name: 'Ki Na Ma', color: 'rojo' }, ]));
	console.log( listGifts('bici coche balón _playstation bici    coche   peluche'));
	// console.log(isValid('bici coche (balón) bici coche peluche'));
	// console.log(createXmasTree(3));
	// console.log(daysToXmas(new Date('Dec 1, 2021')));
	// console.log(sumPairs([3, 5, 7, 2], 10)); // [3, 7]
	// console.log(contains({ estanteria1: { cajon1: { producto1: 'coca-cola', producto2: 'fanta', producto3: 'sprite', }, }, estanteria2: { cajon1: 'vacio', cajon2: { producto1: 'pantalones', producto2: 'camiseta', }, }, },'camiseta'));
	// console.log(maxProfit([39, 18, 29, 25, 34, 32, 5]));
	// console.log(groupBy([6.1, 4.2, 6.3], Math.floor));
	// console.log(getCoins(51));
	// console.log(shouldBuyFidelity(1));
	// console.log(getMinJump([5, 3, 6, 7, 9]));
	// console.log(wrapGifts(['📷', '⚽️']));
	// console.log(missingReindeer([0, 2, 3]));
	// console.log(checkSledJump([1, 2, 3, 2, 1]));
	// console.log(decodeNumbers(';.W'));
	// console.log(countPackages([['dapelu', 5, ['midu', 'jelowing']],['midu', 2, []],['jelowing', 2, []],],'dapelu'));
	// console.log(fixFiles(['file', 'file(1)', 'icon', 'icon(1)', 'icon(1)']));
	// console.log(learn(10, [2, 3, 8, 1, 4]));
	// console.log(pangram('Extraño pan de col y kiwi se quemó bajo fugaz vaho'));
	// console.log(canCarry(4, [[2, 5, 8],[3, 6, 10],]));
})();